package module5;

import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;

/**
 * @author Mark Forster
 *
 *         The Movie class.
 * 
 *         Defines the movie object which is used to manage the
 *         list of movies.  
 * 
 *         The attributes of the Movie class are...
 * 
 *         id 			The unique movie ID which is automatically generated by the system.
 *         name			The name of the movie.
 *         description	A description of the movie.
 *         rating		The rating (1-10) of the movie.
 *
 */
public class Movie {

	private SimpleIntegerProperty id;
	private SimpleStringProperty name;
	private SimpleStringProperty description;
	private SimpleIntegerProperty rating;

    /**
     * The constructor for the class.
     * 
     * @param	id 			The unique movie ID which is automatically generated by the system.
     * @param	name		The name of the movie.
     * @param	description	A description of the movie.
     * @param	rating		The rating (1-10) of the movie.
     */
	public Movie(int id, String name, String description, int rating) {
		this.id = new SimpleIntegerProperty(id);
		this.name = new SimpleStringProperty(name);
		this.description = new SimpleStringProperty(description);
		this.rating = new SimpleIntegerProperty(rating);
		
		View.LOGGER.info("\nAdding a new movie to the database...\n" +
		                 "ID:          " + Integer.toString(id) + "\n" +
		                 "Movie Name:  " + name + "\n" +
		                 "Description: " + description + "\n" +		
		                 "Rating:      " + Integer.toString(rating) + "\n");

	}
	
    /**
     * Returns the movie ID.
     * 
     */
	public Integer getId() {
		return id.get();
	}

    /**
     * Returns the name of the movie.
     * 
     */
	public String getName() {
		return name.get();
	}
	
    /**
     * Returns the description of the movie.
     * 
     */
	public String getDescription() {
		return description.get();
	}
	
    /**
     * Returns the rating of the movie.
     * 
     */
	public Integer getRating() {
		return rating.get();
	}
}
